"""Initial migration

Revision ID: 1171d30871a2
Revises: 
Create Date: 2026-10-05 14:17:39.684744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1171d30871a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('hazard', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('areas', sa.String(), nullable=False),
    sa.Column('issued_at', sa.String(), nullable=False),
    sa.Column('valid_until', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('acknowledged', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_alerts_id'), 'hazard_alerts', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('overall', sa.String(), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('hazards_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_snapshots_id'), 'risk_snapshots', ['id'], unique=False)
    op.create_table('risk_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('centroid', sa.Text(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('factors_json', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_zones_id'), 'risk_zones', ['id'], unique=False)
    op.create_table('current_weather',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('feels_like_c', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('rainfall_24h_mm', sa.Float(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.String(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('pressure_hpa', sa.Float(), nullable=False),
    sa.Column('visibility_km', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_weather_id'), 'current_weather', ['id'], unique=False)
    op.create_table('forecast_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('rain_chance_pct', sa.Float(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('dominant_risk', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_slots_id'), 'forecast_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_slots_id'), table_name='forecast_slots')
    op.drop_table('forecast_slots')
    op.drop_index(op.f('ix_current_weather_id'), table_name='current_weather')
    op.drop_table('current_weather')
    op.drop_index(op.f('ix_risk_zones_id'), table_name='risk_zones')
    op.drop_table('risk_zones')
    op.drop_index(op.f('ix_risk_snapshots_id'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_hazard_alerts_id'), table_name='hazard_alerts')
    op.drop_table('hazard_alerts')
    # ### end Alembic commands ###
